name: Lint

on:
  # NOMERGE
  # push:
  # pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install tox
        run: pip install tox
      - name: Run black
        run: tox -e black
      - name: Run flake8
        run: tox -e flake8
      - name: Run mypy
        run: tox -e mypy
      - name: Install requirements to generate docs
        run: sudo apt-get install -y libgeos-dev
      - name: Check documentation
        run: tox -e docs
